channels:
- conda-forge
dependencies:
- python~=3.9.6
- pip>=22.0.4
- pycairo>=1.21.0
- anndata>=0.7.4
- numpy>=1.17.0
- matplotlib-base>=3.1.2
- pandas>=0.21
- scipy>=1.4
- seaborn
- h5py>=3
- tqdm
- scikit-learn>=0.22
- statsmodels~=0.13.1
- patsy
- networkx>=2.3
- natsort
- joblib
- numba>=0.41.0
- umap-learn>=0.3.10
- packaging
- setuptools-scm
- black>=20.8b1
- docutils
- sphinx<4.2,>=4.1
- sphinx_rtd_theme>=0.3.1
- python-igraph~=0.9.8
- leidenalg
- louvain!=0.6.2,>=0.6
# - scikit-misc~=0.1.4
- pytest>=4.4
- pytest-nunit
- dask-core!=2.17.0
- fsspec
- zappy
- zarr
- profimp
- flit-core
- ipywidgets
- pip:
  - flit
  - session-info
  # - bbknn
  - scanpydoc<0.7.6,>=0.7.4
  # - harmonypy
  # - magic-impute>=2.0
  # - cudf
  # - cuml
  # - cugraph
  # - scanorama
  # - scrublet
  - torch>=1.8.0
  - scikit-misc>=0.1.3
  - scanpy>=1.7.2
  - notebook
name: scTenifold

